In [2]:
import torch

In [ ]:
def remove_projection(H, x):
    """
    H: (v, n)
    x: (n,)

    Returns:
        H_perp: (v, n), with the component along x removed
    """
    return H - ((H @ x) / torch.dot(x, x)).unsqueeze(1) * x


v = 5
n = 2

H = torch.rand((v, n))
x = torch.tensor([1.0, 0.0])

out = remove_projection(H, x)

print(H)
print(x)
print(out)

tensor([[0.3569, 0.4830],
        [0.8082, 0.1312],
        [0.5767, 0.4767],
        [0.4101, 0.3206],
        [0.5676, 0.8039]])
tensor([1., 0.])
tensor([[0.0000, 0.4830],
        [0.0000, 0.1312],
        [0.0000, 0.4767],
        [0.0000, 0.3206],
        [0.0000, 0.8039]])
